spring.application.name=ms-proveedores

spring.datasource.url=${SPRING_DATASOURCE_URL:postgresql://postgres:uIciXTZVbgKaLgOtzyBBEfmbuyAExdbT@postgres.railway.internal:5432/railway}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:uIciXTZVbgKaLgOtzyBBEfmbuyAExdbT}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis deshabilitado
# spring.cache.type=none
# spring.redis.host=localhost
# spring.redis.port=6379
# spring.data.redis.timeout=60000
# spring.cache.redis.time-to-live=3600000

server.port=8085

logging.level.org.springframework.web=DEBUG




